pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Abhishek-bbl/giftbloom-frontend.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Run App') {
            steps {
                sh '''
                nohup npm start > output.log 2>&1 &
                '''
            }
        }
    }
}